#spring:
#  application:
#    name: oauth2-server
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.2.240:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
spring:
  application:
    name: oauth2-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.2.240:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
server:
  port: 1520

mybatis:
  config-location: classpath:mybatis-config:xml
  configuration:
    # resultMap返回null字段
    map-underscore-to-camel-case: true
    return-instance-for-empty-row: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl